version: "3"
services:
  shimpyo-db:
    container_name: shimpyo-db
    image: mariadb:10
    env_file:
      - .env
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_DATABASE=shimpyo
      - TZ=Asia/Seoul
    volumes:
      - ./mariadb/config:/etc/mysql/conf.d
      - ./mariadb/data:/var/lib/mysql
    ports:
      - "3307:3306"
    restart: always

  shimpyo-redis:
    container_name: shimpyo-redis
    image: redis:6
    ports:
      - "6379:6379"
    restart: always
